OPENAI_API_KEY = ""
ANTHROPIC_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyCdUgU4Yj2RxMyaspZBjzlB530OIzQ69LM"
