OPENAI_API_KEY = "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"
ANTHROPIC_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyCdUgU4Yj2RxMyaspZBjzlB530OIzQ69LM"
